### ISSUE TITLE
关注树洞丢失

### ISSUE THREAD

**Issue by wky9710** [pkuhelper-web/webhole#10]
清了一次浏览器缓存以后关注就全没了
相关信息：毕业生，本校保研，大约1个月前用研究生账号登录后仍能看到之前订阅
但这次清完缓存全部消失，包括本科生阶段和研究生阶段的关注
请问下可能的原因及解决方法？谢谢~
如需要可提供学号信息

**Comment by xmcp** [comment]
请提供**完整、客观**的问题描述谢谢

**Comment by xmcp** [comment]
这个问题可能是后端瞎删数据库引起的，我再去确认下：
- PKUHelper客户端和网页版登录树洞，关注都显示为空是吗？
- 请提供所有（之前和现在的）学号。

**Comment by wky9710** [comment]
一直用的是网页端，网页端不行，helper客户端刚试了可以
// 现在网页端我的两个关注是发生问题之后又加上去的

1500012850 --> 1901213327

今天大约16:00，chrome清理缓存之后关注消失；之前一直在刷树洞无异常
（以及之前清理缓存时没遇到类似问题）

**Comment by xmcp** [comment]
？你是不是登录错账号了

在网页版里重新一下试试

**Comment by wky9710** [comment]
本科生的账号早就不能登陆了……现在一直是研究生账号，大约7月初就是这个账号了
应该是本科生和研究生的关注内容不共享吧……
刚发现我的helper客户端使用本科生学号登录的，网页端在7月初重新用研究生账号登陆过，但关注未丢失，这次再登陆一次就没了

**Comment by xmcp** [comment]
本科生和研究生的关注内容不共享 ✓

目前本科生和研究生被认为是独立的账号，关注内容应当是独立的。
不如说原来关注未丢失才是bug（可能是浏览器缓存）。
