### ISSUE TITLE
a+字母 搜索似乎会忽略a

### ISSUE THREAD

**Issue by CPCer** [pkuhelper-web/webhole#12]
![image](https://user-images.githubusercontent.com/8787958/67392834-d90e2c00-f5d3-11e9-8e17-7fe34bcb6ab9.png)

![image](https://user-images.githubusercontent.com/8787958/67392867-e5928480-f5d3-11e9-8908-62c8e9748e66.png)

一直试到f好像都是这样

**Comment by CPCer** [comment]
a+中文正常。
加英文双引号无效。

Thx for ur attention!

**Comment by xmcp** [comment]
搜索问题是后端的经典bug，与网页版树洞没有关系。
