### ISSUE TITLE
点击“教室”之后白屏

### ISSUE THREAD

**Issue by initzhang** [pkuhelper-web/webhole#13]
iOS 13.1.3 、iPhone8、Safari浏览器   
进入主页之后点击最上方的“教室”按钮会白屏   
但是复制网址后，在微信的webview中打开、在电脑端打开看都是正常的  
录制了一个视频压缩了下：  
[RPReplay_Final1571891934.MP4.zip](https://github.com/pkuhelper-web/webhole/files/3765755/RPReplay_Final1571891934.MP4.zip)

辛苦！

**Comment by xmcp** [comment]
无法复现，建议尝试刷新、连校园网、清除浏览器缓存等操作。
如果方便的话，可以连接电脑用macOS Safari看一下具体错误是什么。
