### ISSUE TITLE
回复发送失败后洞的回复数问题

### ISSUE THREAD

**Issue by AllanChain** [pkuhelper-web/webhole#17]
rt。不知道是不是前端问题。

洞里回复因过长而发送失败后，显示的该洞回复个数不对，但刷新后会恢复正常。

如
![Screenshot_2020-01-12-14-23-37](https://user-images.githubusercontent.com/36528777/72214953-6c0d9100-3547-11ea-9981-751dcc8c986a.png)
![Screenshot_2020-01-12-14-23-46](https://user-images.githubusercontent.com/36528777/72214954-6e6feb00-3547-11ea-9a06-23d2b7ed1354.png)

![Screenshot](https://user-images.githubusercontent.com/36528777/72214900-416f0880-3546-11ea-9949-177350e1afaa.png)
![Screenshot_2020-01-12-14-27-37](https://user-images.githubusercontent.com/36528777/72214982-c4dd2980-3547-11ea-9325-712ca5c49f75.png)

**Comment by xmcp** [comment]
后端的锅，半年前我就发现过了……
@jimmielin 快修

**Comment by AllanChain** [comment]
```
 reply: update_count ? ''+json.data.length : prev.info.reply,
```
求问为什么在加载树洞的时候，`update_count` 要设成 false？

**Comment by jimmielin** [comment]
确认是后端问题
