### ISSUE TITLE
20级新生stu邮箱无法使用邮箱功能

### ISSUE THREAD

**Issue by Acid-Blue** [pkuhelper-web/webhole#26]
20级开始邮箱为@stu.pku.edu.cn，外包给了网易，登录地址：mail.stu.pku.edu.cn
网页版指向的仍然是mail.pku.edu.cn，望解决，多谢。

**Comment by xmcp** [comment]
登录接口由 https://isop.pku.edu.cn/ 提供，请联系计算中心解决。
（不如说邮件验证码已经挂了几个月了他们都没人管）

**Comment by yangtang-special** [comment]
北大每个学生都会经常使用这个平台吗？（听说是本校学生开发的）
