### ISSUE TITLE
禁言异议

### ISSUE THREAD

**Issue by jihufda** [pkuhelper-web/webhole#27]
我发了一条没有任何脏话或者攻击性语言的树洞，仅仅是对绩点表示了焦虑，就被大家举报了
但是现在我需要使用树洞，答疑明天的高数考试，所以能不能麻烦管理员再次斟酌事实，把我暂时放出来，我愿意在16号开始为期3天的紧闭（现在是两天）。
谢谢！

**Comment by xmcp** [comment]
关于举报的疑问请按封禁提示联系helper at pku.edu.cn处理
