### ISSUE TITLE
helper邮箱没有人回复

### ISSUE THREAD

**Issue by jihufda** [pkuhelper-web/webhole#28]
您好，helper的邮箱没有人回复应该怎么办呢，真的很着急用树洞，因为明天就要考试了。
况且我认为自己是无辜被禁言的，完全是因为我的发言踩到某些人的焦虑点上了。洞里还有很多对我人身攻击，辱骂我的人，却没有被禁言，这不公平。
希望能尽快联系到管理员~

**Comment by xmcp** [comment]
七、 用户不得利用P大树洞上传、发布、传播如下干扰P大树洞正常运营，或者侵害其他用户或第三方合法权益，或者经举报、申诉并核实准确的内容：
1. 引起其他用户不适并受到多次举报的；
