### ISSUE TITLE
API数据问题

### ISSUE THREAD

**Issue by destoryD** [pkuhelper-web/webhole#30]
我想基于PKUHELPER做一套我们学校的webhole,但是调试过程中发现如果没有api.php返回格式数据的话会很困难，可以提供一下这些api返回的数据样例吗？感谢

**Comment by AllanChain** [comment]
@destoryD 为什么不参考 [thuhole](https://github.com/thuhole) 呢？人家也是基于 P 大树洞，而且前后端都开源，参考起来更方便（手动滑稽）

**Comment by xmcp** [comment]
暂时不能提供

**Comment by xmcp** [comment]
建议参考其他项目#=_= pkuhelper的祖传后端现在返回格式挺乱的，可以重新写一个，就是需要调整相应前端代码

**Comment by thuhole** [comment]
@destoryD 现在树洞的前端后端都还不稳定，而且还在频繁开发和更新，建议可以再等几个月等树洞出现成熟的开源前端和后端。
