### ISSUE TITLE
希望在新学期恢复“空闲教室”的顶端快捷栏地位

### ISSUE THREAD

**Issue by CastleStar14654** [pkuhelper-web/webhole#31]
![image](https://user-images.githubusercontent.com/50725189/93707763-ed500580-fb63-11ea-86e8-0e31ea4656bd.png)
鉴于2020年9月绝大多数P大学生返校，自习需求日益增长；与此同时，新学期开始上课后，教学楼空闲教室情况愈发变换莫测，便捷查询空教室的需求重新显现。
今年4月，“不咕”功能替换了“空闲教室”在网页版树洞顶端的快捷栏的位置。虽然，[空闲教室的页面](https://pkuhelper.pku.edu.cn/spare_classroom)仍在运营，但其访问方式对网页版手机端用户不甚友好。
一人血书@xmcp 把“空闲教室”加回去。

**Comment by xmcp** [comment]
![image](https://user-images.githubusercontent.com/6646473/93715612-ec879580-fb9c-11ea-8c55-57f9abea1f43.png)

现在贵校空闲教室API似乎还没有数据
等有了数据就会换回来的

**Comment by xmcp** [comment]
我看isop的数据已经有了，已经加回来了
