### ISSUE TITLE
无法查看树洞评论

### ISSUE THREAD

**Issue by yuanfei-Wang** [pkuhelper-web/webhole#32]
登录树洞后显示“正在进行人机验证”，能够看到树洞主楼内容，但是无法看到评论。注销重启皆无效，也关闭了所有代理。

**Comment by yuanfei-Wang** [comment]
![hole error](https://user-images.githubusercontent.com/40728481/95546101-4eb41780-0a32-11eb-9a07-f7a720f9aa4b.png)

**Comment by xmcp** [comment]
树洞使用ReCaptcha来进行人机验证。请检查网络环境（能否访问https://recaptcha.net/）以及是否打开了广告屏蔽软件，顺便可以看一下控制台有没有显示错误。
