### ISSUE TITLE
举报自己的树洞会被禁言？

### ISSUE THREAD

**Issue by xiaotianxt** [pkuhelper-web/webhole#33]
今天看到了置顶树洞，果断举报了自己的几条涉及到个人信息的树洞，然后发现自己被禁言了？
![3111603707023_ pic](https://user-images.githubusercontent.com/17041194/97159920-8a7f0900-17b6-11eb-983a-a878b070c59c.jpg)

**Comment by xmcp** [comment]
按照管理要求，删自己的洞确实会禁言，目的是防止滥用这个功能逃避审核（冲塔被发现之前自删）。我记得自删应该只封一天来着，我去问问。
我不太负责管理这方面的工作，如果你这几天确实需要使用树洞，可以把自己的情况邮件告诉 helper at pku.edu.cn

**Comment by xiaotianxt** [comment]
> 按照管理要求，删自己的洞确实会禁言，目的是防止滥用这个功能逃避审核（冲塔被发现之前自删）。我记得自删应该只封一天来着，我去问问。
> 我不太负责管理这方面的工作，如果你这几天确实需要使用树洞，可以把自己的情况邮件告诉 helper at pku.edu.cn

好的，我已经给helper发邮件了。

还有个小问题，我的禁言时间并不是一天（因为曾经冲塔还是泄露个人信息来着），这次是4天。自己删掉帖子会导致未来的禁言时长++吗？
