### ISSUE TITLE
网页版一直进行人机验证，手机版一直让我安全验证

### ISSUE THREAD

**Issue by flowingwings** [pkuhelper-web/webhole#34]
手机版每条树洞的评论都只有一条，是Helper让我在网页版进行安全验证。
网页版的某些树洞边上出现“进行人机验证（完成）”字样，点击会短暂出现“加载中”然后回去。账户-强制检查更新就只刷新一下页面，然后还是不能查看评论/回复。
网页版所有树洞都不能查看评论/回复，回复会出现“进行人机验证（完成）”和“回复加载失败 CAPTCHA”字样。

**Comment by flowingwings** [comment]
我无法访问recaptcha.net，开关代理都不行……

**Comment by xmcp** [comment]
据我所知recaptcha.net用校园网和移动4G都能正常访问，建议检查dns设置和浏览器插件，或者换台设备试试

**Comment by flowingwings** [comment]
已解决，换了个浏览器，chrome不知道为啥不行。
