### ISSUE TITLE
一直提示登录失败

### ISSUE THREAD

**Issue by 911347123** [pkuhelper-web/webhole#8]
![image](https://user-images.githubusercontent.com/43485174/60397987-dcddf480-9b85-11e9-8a92-3814ab790daf.png)

**Comment by xmcp** [comment]
首先，请确认“登录失败”前页面是否有其他错误提示。
如果没有，请尝试PKUHelper客户端是否能正常登录。
如果客户端可以登录，请确认用Chrome浏览器是否有这个问题。
如果Chrome没有问题，请尝试升级或更换浏览器；如果Chrome也有同样的问题，请按F12然后复制Console内的错误信息。

**Comment by 911347123** [comment]
是浏览器的问题，edge登陆一直失败，换成chrome之后好了，谢谢。

发自我的 iPad
