### ISSUE TITLE
一直提示访问参数无效

### ISSUE THREAD

**Issue by weiluoning** [pkuhelper-web/webhole#9]
![CC7D6385-697E-4ACA-9D08-EE0120695B9B](https://user-images.githubusercontent.com/52388187/60404029-0d9a4a00-9bd7-11e9-8936-45d0df8af119.png)
![797E2EB4-8D73-45F4-B046-2DE284A1F470](https://user-images.githubusercontent.com/52388187/60404030-0e32e080-9bd7-11e9-91c1-4c7facc42f23.png)
iOS客户端与网页版显示如图

**Comment by xmcp** [comment]
建议检查时间日期设置
